---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server/

images:
  - name: blackbox-exporter
    newName: quay.io/prometheus/blackbox-exporter
    newTag: "v0.24.0"

...
