---
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes:
        - 200
        - 301
        - 302
        - 303
      method: GET
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      preferred_ip_protocol: ip4
      tls_config:
        insecure_skip_verify: true

...
