---
apiVersion: v1
kind: Service

metadata:
  name: blackbox-exporter
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/component: server

spec:
  selector:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/component: server

  ports:
    - name: http
      port: 9115

...
