---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: blackbox-exporter
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/component: server

spec:
  endpoints:
    - port: http
      scheme: http
      interval: 30s

  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
      app.kubernetes.io/component: server

...
